### ISSUE TITLE
ML kit for android

### ISSUE THREAD

**Issue by benkhachouch** [tuarua/ML-ANE#6]
Hello!
Have you plan for google ML  kit Ane for Android?
Thanks.

**Comment by leossmith** [comment]
It would be awesome. ML from google is also part of Firebase.

**Comment by tuarua** [comment]
I will look at this at some point.
It has only just been added in beta to Firebase 2 weeks ago.

**Comment by benkhachouch** [comment]
Thanks you .i told with myflashlabs. They  have plan for this..in future.
